name: Sonarcloud scan

on:
  workflow_run:
    workflows:
      - KinD tests
    types:
      - completed

jobs:
  sonarcloud:
    uses: stolostron/governance-policy-framework/.github/workflows/sonarcloud.yml@499dd1258fa26c15beafc6630f8bf75ec6db6c83 # main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
